config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "pages#home"

  devise_for :users, controllers: { confirmations: 'users/confirmations', registrations: 'users/registrations' }

  post "tasks/:id/toggle", to: "tasks#toggle"
  resources :tasks, except: [:new, :show]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :integer          not null, primary key
#  completed   :boolean          default(FALSE)
#  description :string(100)      not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer          not null
#
# Indexes
#
#  index_tasks_on_user_id  (user_id)
#
# Foreign Keys
#
#  user_id  (user_id => users.id)
#
class Task < ApplicationRecord
  belongs_to :user, touch: true

  validates :description, length: { in: 3..100}
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string           default("")
#  last_name              :string           default("")
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  unconfirmed_email      :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_confirmation_token    (confirmation_token) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable

  has_many :tasks,  dependent: :destroy

  has_person_name
  normalizes :first_name, :last_name,  with: -> { _1.downcase.titleize }

  broadcasts_refreshes

  def nickname
    name ? name.familiar : email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  private

  def after_sign_in_path_for(resource)
    tasks_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :redirect_if_logged_in

  def home;end

  private

  def redirect_if_logged_in
    if user_signed_in?
      redirect_to tasks_path, alert: "You need to sign out before continuing."
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[toggle edit update destroy]

  def index
    @tasks = current_user.tasks.order(:completed)
    @task = current_user.tasks.new
  end

  def create
    @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'Task created successfully' }
      else
        @tasks = current_user.tasks.order(:completed)
        format.html { render :index, status: :unprocessable_entity }
      end
    end
  end

  def toggle
    @task.update(completed: params[:completed])
  end

  def edit
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        message = "Task updated successfully"
        flash.now[:notice] = message

        format.html { redirect_to tasks_path, notice: message }
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace(@task) ,
            turbo_stream.update(:flash_msg, partial: "shared/flash" )
        ]
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    message = "Task deleted successfully"
    flash.now[:notice] = message

    respond_to do |format|
      format.html { redirect_to tasks_path, notice: message }
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.remove(@task),
          turbo_stream.update(:flash_msg, partial: "shared/flash" )
      ]
      end
    end
  end

  private

  def task_params
    params.require(:task).permit(:description)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  private
  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource)
    tasks_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected
  # after updating the profile
  def after_update_path_for(resource)
    tasks_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def css_class_for_flash(type)
    case type
    when "notice"
      "bg-green-50 text-green-500 dark:bg-gray-900 dark:text-lime-600 dark:backdrop-blur-xl"
    when "alert"
      "bg-amber-50 text-amber-500 dark:bg-gray-900"
    end
  end

  def icon_for_flash(type)
    case type
    when "notice"
      render "shared/svg/check_mark", classes: "size-5"
    when "alert"
      render "shared/svg/info"
    end
  end

  def delay_flash(message)
    (message.length.fdiv(10).ceil * 1000).to_s
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_bg_polygon_bottom.html.erb
<div class="absolute inset-x-0 bottom-0 -z-10 transform-gpu overflow-hidden blur-3xl" aria-hidden="true">
  <div class="relative left-[80%] lg:left-[75%] xl:left-[70%] w-[20.125rem] lg:w-[30.1875rem] xl:w-[40.1875rem] aspect-[1155/678] -translate-x-1/2 bg-gradient-to-tr from-primary-400 to-secondary-800 lg:opacity-65 xl:opacity-50 dark:opacity-30" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
</div>

app/views/layouts/_bg_polygon_top.html.erb
<div class="absolute inset-x-0 -top-64 md:-top-96 lg:-top-80 -z-10 transform-gpu overflow-hidden blur-3xl" aria-hidden="true">
  <div class="relative left-[calc(50%-11rem)]  md:left-[calc(50%-30rem)] lg:left-[calc(50%-40rem)] w-[56.1875rem] md:w-[76.1875rem] aspect-[1155/678] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-primary-300 to-secondary-700 opacity-25 dark:opacity-30" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
</div>

app/views/layouts/_footer.html.erb
<% unless user_signed_in? %>
  <footer class="grid gap-7 place-items-center p-7 md:gap-10 mt-10 bg-primary-200/50 dark:bg-gray-600/10">
    <%# Main Content %>
    <div class="grid gap-7 place-items-center md:flex md:w-full lg:w-2/3 xl:w-1/2 md:items-center md:justify-between">
      <%# Logo %>
      <div class="flex items-center text-3xl md:text-2xl text-primary-950 dark:text-primary-50">
        <%= image_tag("logo.png", class: "w-8 h-8 mr-2", alt: "logo") %>
        <h1 class="tracking-wide">TickityTick</h1>
      </div>

      <%# Links %>
      <ul class="flex flex-wrap items-center text-sm md:text-base">
          <li>
              <a href="#" class="link text-secondary-800/80 dark:text-primary-300/90 me-4 md:me-6">About</a>
          </li>
          <li>
              <a href="#" class="link text-secondary-800/80 dark:text-primary-300/90 me-4 md:me-6">Privacy Policy</a>
          </li>
          <li>
              <a href="https://www.buymeacoffee.com/juzershakir" target="_blank" class="link text-secondary-800/80 dark:text-primary-300/90 me-4 md:me-6">Support</a>
          </li>
          <li>
              <a href="mailto:juzershakir.webdev@gmail.com" target="_blank" class="link text-secondary-800/80 dark:text-primary-300/90">Contact</a>
          </li>
      </ul>
    </div>

    <%# Divider %>
    <hr class="divider" />

    <%# COPYRIGHT %>
    <copy class="text-xs text-center italic text-primary-600 dark:text-gray-400">
      &copy; <%= Date.today.year %> TickityTick™.
      <span class="text-sm text-primary-700 dark:text-gray-200/90">
        Developed & designed by Juzer Shakir.
      </span>
    </copy>
  </footer>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="scroll-smooth">
  <head>
    <title>TickityTick</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%# only updates those DOM elements that have been modified %>
    <meta name="turbo-refresh-method" content="morph">
    <%# Preserves scroll position %>
    <meta name="turbo-refresh-scroll" content="preserve">

    <!-- Open Graph Tags - Displays rich preview of this site when link is shared -->
    <meta property="og:title" content="TickityTick" />
    <meta property="og:type" content="website" />
    <meta property="og:description" content="A distraction-free task manager designed to help you capture fleeting ideas without breaking your focus." />
    <meta property="og:url" content="<%= root_url %>" />
    <meta property="og:image" content="<%= image_url("og-image.png") %>" />

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="TickityTick" />
    <meta name="twitter:description" content="A distraction-free task manager designed to help you capture fleeting ideas without breaking your focus." />
    <meta name="twitter:url" content="<%= root_url %>" />
    <meta name="twitter:image" content="<%= image_url("og-image.png") %>" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

    <%# Favicon Ico %>
    <%= favicon_link_tag asset_path("favicon.ico") %>

    <%# Fonts %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <%# Titillium & Nunito Sans Fonts (All Weights) from https://fonts.google.com/ %>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000&family=Titillium+Web:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700&display=swap" rel="stylesheet">
  </head>

  <body class="font-sans dark:text-gray-300 bg-primary-50 dark:bg-gray-900 selection:bg-secondary-200 selection:text-primary-900 dark:selection:bg-primary-200 dark:selection:text-primary-800">
    <!-- Top Navbar for Medium or higher screen size -->
    <%= render "shared/top_navbar" %>

    <%= render "shared/flash" %>

    <%= render "layouts/bg_polygon_top" %>

    <main class="grid gap-10 lg:gap-16 justify-items-center p-5">
      <%= yield %>
    </main>

    <%= render "layouts/bg_polygon_bottom" %>

    <%= render "layouts/footer" %>

    <!-- Bottom Navbar for Mobile Screen -->
    <%= render "shared/bottom_navbar" %>
  </body>
</html>

app/views/pages/_cta.html.erb
<div class="flex flex-col sm:flex-row sm:justify-center">
  <%= link_to  new_user_session_path, class: "inline-flex items-center justify-center px-5 py-3 capitalize leading-none text-base md:text-lg xl:text-xl font-medium text-center text-white rounded-lg bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 dark:focus:ring-primary-900 shadow-xl dark:shadow-md shadow-secondary-600/40 dark:shadow-secondary-500/35 focus:shadow-none hover:shadow-none transition duration-750 hover:translate-y-1 dark:hover:translate-y-0.5" do %>
    <%= message %>
  <%= render "shared/svg/right_arrow" %>
  <% end %>
</div>

app/views/pages/home.html.erb
<section class="grid gap-20 md:gap-28 justify-items-center items-center text-center py-5 px-4 lg:py-16 lg:px-12">
  <%# Header %>
  <div class="flex items-center text-4xl font-semibold text-primary-950 dark:text-white">
    <%= image_tag("logo.png", class: "w-12 h-12 mr-2", alt: "logo") %>
    <h1 class="tracking-wide">TickityTick</h1>
  </div>

  <%# Header Content %>
  <div class="space-y-7 lg:space-y-14 tracking-wide">
    <%# Heading %>
    <h2 class="text-4xl font-bold text-secondary-600 md:text-5xl lg:text-6xl dark:text-secondary-100">
      <span class="relative whitespace-nowrap text-primary-900 dark:text-primary-400">
      <%= render "shared/svg/scribble_underline"%>
        <span class="relative">Focus</span>
      </span>
      on What Matters.
      <br>
      <span class="relative whitespace-nowrap text-primary-900 dark:text-primary-400">
      <%= render "shared/svg/scribble_underline"%>
        <span class="relative">Capture</span>
      </span>
      Tasks Quickly.
    </h2>

    <%# Description %>
    <p class="max-w-screen-md xl:max-w-screen-lg text-xl font-normal text-secondary-900/90 lg:text-2xl sm:px-16 xl:px-48 dark:text-secondary-50">
      A distraction-free task manager designed to help you capture fleeting ideas without breaking your focus.
    </p>
  </div>

  <%# CTA %>
  <%= render "cta", message: "start capturing task today" %>

    <%# divider %>
  <hr class="divider">

  <%# Why %>
  <div class="space-y-8 md:space-y-14 lg:space-y-16">
    <h2 class="text-balance text-2xl md:text-3xl lg:text-4xl font-semibold text-primary-950 dark:text-primary-300">Why TickityTick? 🤔</h2>
    <div class="space-y-7 md:space-y-10 lg:space-y-14">
      <p class="text-pretty text-lg md:text-xl lg:text-2xl text-secondary-950 dark:text-secondary-100 leading-10 tracking-wide md:tracking-wider lg:max-w-2xl">
        Ever have a task idea or find a bug while working, but struggle to jot it down without breaking your flow?
      </p>
      <p class="text-pretty text-lg md:text-xl lg:text-2xl text-secondary-950 dark:text-secondary-100 leading-10 tracking-wide md:tracking-wider lg:max-w-2xl">
        TickityTick is a web app designed to help you stay focused and capture those fleeting ideas with minimal effort.
      </p>
      <p class="text-pretty text-lg md:text-xl lg:text-2xl text-secondary-950 dark:text-secondary-100 leading-10 tracking-wide md:tracking-wider lg:max-w-2xl">
        Enhances productivity for developers, designers, and content creators by providing a streamlined interface to log tasks, bugs, and inspirations quickly.
      </p>
    </div>
  </div>

  <%# divider %>
  <hr class="divider">

  <%# Benefits %>
  <div class="grid gap-8 md:gap-10 lg:gap-14 xl:gap-20 max-w-screen-xl">
      <h2 class="text-balance text-2xl md:text-3xl lg:text-4xl font-semibold text-primary-950 dark:text-primary-300">Benefits of using TickityTick</h2>
      <div class="space-y-8 md:space-y-14 lg:space-y-16 xl:space-y-0 xl:grid xl:grid-cols-3 xl:gap-10">
          <div class="xl:space-y-7 lg:space-y-5 space-y-3">
              <%= render "shared/svg/tick" %>
              <h3 class="md:text-start xl:text-center text-xl md:text-2xl lg:text-3xl font-semibold tracking-wider text-primary-950 dark:text-primary-600">Streamlined Interface</h3>
              <p class="text-pretty md:text-start xl:text-center text-lg md:text-xl text-secondary-950 dark:text-secondary-100 leading-7 tracking-wide">
                Simple and easy-to-use interface minimizes disruption to your workflow.
              </p>
          </div>
          <div class="xl:space-y-7 lg:space-y-5 space-y-3">
              <%= render "shared/svg/bolt" %>
              <h3 class="md:text-start xl:text-center text-xl md:text-2xl lg:text-3xl font-semibold tracking-wider text-primary-950 dark:text-primary-600">Rapid Capture</h3>
              <p class="text-pretty md:text-start xl:text-center text-lg md:text-xl text-secondary-950 dark:text-secondary-100 leading-7 tracking-wide">
                Perfect for capturing quick reminders or task ideas that pop into your head.
              </p>
          </div>
          <div class="xl:space-y-7 lg:space-y-5 space-y-3">
              <%= render "shared/svg/device_phone" %>
              <h3 class="md:text-start xl:text-center text-xl md:text-2xl lg:text-3xl font-semibold tracking-wider text-primary-950 dark:text-primary-600">Responsive Design</h3>
              <p class="text-pretty md:text-start xl:text-center text-lg md:text-xl text-secondary-950 dark:text-secondary-100 leading-7 tracking-wide">
                Ensures a smooth experience on both desktop, laptop, tablet & mobile devices.
              </p>
          </div>
      </div>
  </div>

  <%# CTA %>
  <%= render "cta", message: "enhance my productivity"%>

  <%# divider %>
  <hr class="divider">

  <%# User count %>
  <h2 class="text-3xl italic md:text-4xl font-bold leading-relaxed tracking-wide text-primary-700/90 dark:text-primary-300/90">
    Trusted by 50+ users worldwide
  </h2>

  <%# Testimonials %>
  <div class="max-w-screen-lg mx-auto text-center space-y-10 lg:space-y-14">
    <%# headings %>
    <hgroup class="space-y-5">
      <h1 class="text-lg md:text-xl lg:text-2xl font-extralight text-primary-950 dark:text-primary-200 uppercase">Testimonials</h1>
      <h2 class="text-2xl md:text-3xl lg:text-4xl font-semibold text-primary-950 dark:text-primary-300">What our happy users say 📢</h2>
    </hgroup>

    <%# main content %>
    <figure class="rounded-lg shadow-xl dark:shadow-lg border border-secondary-600/20 shadow-secondary-600/40 dark:shadow-secondary-300/25 max-w-screen-md mx-auto px-6 md:px-12 lg:px-16 py-10 lg:py-12 bg-secondary-100/70 dark:bg-gray-800">
    <%= render "shared/svg/double_opening_quotation" %>

      <div class="grid gap-2 mt-5 md:mt-2">
        <%# Stars %>
        <div class="flex justify-center items-center my-4 text-yellow-300">
          <%= render "shared/svg/five_stars" %>
        </div>
        <%# Text %>
        <blockquote>
            <p class="indent-8 sm:indent-16 md:indent-20 lg:indent-28 text-start text-lg md:text-xl lg:text-2xl text-secondary-950 dark:text-secondary-100 leading-10 tracking-normal md:tracking-wider">
              "This is a
              <span class="text-transparent bg-clip-text bg-gradient-to-r from-sky-400 to-emerald-600 dark:from-secondary-400 dark:to-primary-600">lifesaver</span>.
              New ideas and tasks pop into my head constantly. Before, I'd scramble for my phone, inevitably getting sucked into social media and losing focus. Now, I can quickly add tasks from my desktop without breaking my flow. It's
              <span class="text-transparent bg-clip-text bg-gradient-to-r from-sky-400 to-emerald-600 dark:from-secondary-400 dark:to-primary-600">simple</span>,
              <span class="text-transparent bg-clip-text bg-gradient-to-r from-sky-400 to-emerald-600 dark:from-secondary-400 dark:to-primary-600">distraction-free</span>,
              and keeps me on top of everything. Plus, it's free! I highly
              <span class="text-transparent bg-clip-text bg-gradient-to-r from-sky-400 to-emerald-600 dark:from-secondary-400 dark:to-primary-600">recommend</span>
              it for anyone who wants to stay
              <span class="text-transparent bg-clip-text bg-gradient-to-r from-sky-400 to-emerald-600 dark:from-secondary-400 dark:to-primary-600">focused</span>
              and
              <span class="text-transparent bg-clip-text bg-gradient-to-r from-sky-400 to-emerald-600 dark:from-secondary-400 dark:to-primary-600"> organized</span>."
            </p>
        </blockquote>
        <%# Logo, name, designation %>
        <figcaption class="flex items-center justify-center mt-6 space-x-3">
            <img class="w-6 h-6 rounded-full" src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/michael-gouch.png" alt="profile picture">
            <div class="flex items-center divide-x-2 divide-gray-500 dark:divide-gray-700">
                <div class="pr-3 font-bold text-lg tracking-wider text-primary-900 dark:text-primary-50">Juzer Shakir</div>
                <div class="pl-3 text-base font-light text-secondary-800 dark:text-secondary-50">Web Developer</div>
            </div>
        </figcaption>
      </div>
    </figure>
  </div>

  <%# CTA %>
  <%= render "cta", message: "maintain my focus" %>
</section>

app/views/shared/_back.html.erb
<div class="flex justify-center">
  <%= link_to :back, class: "group flex items-center gap-1 sm:gap-2 xl:gap-3 text-primary-600 dark:text-primary-500" do %>
    <%= render "shared/svg/left_arrow" %>
    <span class="text-lg sm:text-xl xl:text-2xl font-semibold tracking-wide group-hover:underline group-hover:underline-offset-4">Back</span>
  <% end %>
</div>

app/views/shared/_bottom_navbar.html.erb
<% if current_user %>
  <nav class="md:hidden z-50 flex justify-between items-center fixed w-full bottom-0 px-6 py-3 bg-primary-50 dark:bg-gray-950 border border-primary-200 dark:border-none">
    <%= image_tag "logo.png", class: "w-8 h-8", alt: "Logo" %>

    <%# Dropdown profile menu %>
    <%= render "shared/dropdown", dropdown_classes: "right-0 bottom-10" %>
  </nav>
<% end %>

app/views/shared/_destroy_dialog.html.erb
<dialog data-dialog-target="deleteModal" class="dark:bg-gray-800 bg-primary-100 rounded-lg shadow backdrop:backdrop-blur-sm text-center space-y-4 md:space-y-5 lg:space-y-6 p-4 sm:p-5">
  <!-- Close Button-->
  <button data-action="click->dialog#close" class="text-primary-400 absolute top-2.5 right-2.5 bg-transparent hover:bg-primary-200 hover:text-primary-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-primary-600 dark:hover:text-primary-200" data-modal-toggle="deleteModal">
    <%= render "shared/svg/x_mark", classes: "size-5" %>
  </button>

  <%# Delete Icon %>
  <div class="size-11 md:size-12 lg:size-13 mx-auto">
    <%= render "shared/svg/dustbin" %>
  </div>

  <%# Confirmation Message %>
  <p class="text-gray-500 dark:text-gray-300 md:text-lg lg:text-xl"><%= message %></p>

  <%# Action %>
  <div class="flex justify-center items-center space-x-4">
    <%#  Cancel Button %>
    <button data-action="click->dialog#close" formmethod="dialog" class="py-2 px-3 lg:py-3 lg:px-4 md:text-lg lg:text-xl font-medium rounded-lg border focus:ring-4 focus:outline-none  focus:z-10 focus:ring-primary-300 text-primary-500 bg-white border-primary-200 hover:bg-secondary-100 hover:text-primary-900 dark:bg-gray-700 dark:text-primary-100 dark:border-secondary-500 dark:hover:text-primary-50 dark:hover:bg-gray-600 dark:focus:ring-gray-600">
        No, cancel
    </button>

    <%# Delete Account  Button %>
    <%= button_to "Yes, I'm sure!",
      destroy_path,
      method: :delete,
      data: {"turbo_frame": "_top", "turbo_submits_with": "Deleting..."},
      class: "py-2 px-3 lg:py-3 lg:px-4 md:text-lg lg:text-xl font-medium text-center text-white bg-red-500 dark:bg-red-600 rounded-lg hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300"
    %>
  </div>
</dialog>

app/views/shared/_logo.html.erb
<div class="flex gap-4">
  <%= image_tag("logo.png", class: "w-8 h-8 sm:w-10 sm:h-10 lg:w-12 lg:h-12", alt: "logo") %>
  <span class="text-3xl sm:text-4xl lg:text-5xl font-semibold bg-gradient-text-clip">
    TickityTick
  </span>
</div>

app/views/tasks/_task.html.erb
<turbo-frame id="<%= dom_id task %>"  class="flex justify-between gap-5">
  <%= form_with(model: task, class:"flex items-center gap-1 md:gap-2") do |form| %>
    <%= form.check_box :completed,
      class: "peer/tick mr-2 form-checkbox",
      data: {
        id: task.id,
        action: "tasks#toggle"
      }
      %>

    <span class="max-w-sm leading-6 text-lg md:text-xl text-secondary-900 dark:text-secondary-200 peer-checked/tick:line-through peer-checked/tick:text-secondary-400/55 peer-checked/tick:italic">
      <%= task.description %>
    </span>
  <% end %>

  <%# Actions %>
  <div class="flex gap-5 md:gap-6 lg:gap-7">
    <%# Edit Task %>
    <%= link_to edit_task_path(task), id: "#{task.id}-edit", class: ("invisible" if task.completed) do %>
      <div class="size-5 md:size-6 lg:size-7">
        <%= render "shared/svg/pencil" %>
      </div>
    <% end %>

    <%# Delete Task %>
    <div data-controller="dialog">
      <button class="size-5 md:size-6 lg:size-7" data-action= "click->dialog#open">
        <%= render "shared/svg/dustbin" %>
      </button>

      <%= render "/shared/destroy_dialog", destroy_path: task_path(task), message: "Are you sure you want to delete this task?" %>
    </div>
  </div>
</turbo-frame>